### ISSUE TITLE
error

### ISSUE THREAD

**Issue by metarf** [mach0/polystrip#5]
2021-04-23T21:18:50     WARNING    Traceback (most recent call last):
              File "E:\Portable\QGIS-3.4.11-64bit\qgisconfig\profiles\default/python/plugins\polystrip\poly_strip.py", line 244, in run
              self.dlg.polystrip(layer)
              File "E:\Portable\QGIS-3.4.11-64bit\qgisconfig\profiles\default/python/plugins\polystrip\poly_strip_dialog.py", line 57, in polystrip
              get_all_pages(layer, width, height, srid, coverage, covstart)
              File "E:\Portable\QGIS-3.4.11-64bit\qgisconfig\profiles\default/python/plugins\polystrip\poly_strip_alg.py", line 79, in get_all_pages
              azimuth = startpoint.asPoint().azimuth(endpoint.asPoint())
             ValueError: Null geometry cannot be converted to a point.

**Comment by mach0** [comment]
hi and thanks for your report.
Could you please describe what you did and where the error happened?
With only the error I can see that something happened but I can hardly reproduce it.

**Comment by mach0** [comment]
closed due to no response
